version: "3"

services:
    web:
        image: nginx:alpine
        container_name: nginx-instagram
        ports: 
            - "80:80"
        volumes:
            - ../instagram:/app
            - ./conf/site.conf:/etc/nginx/conf.d/default.conf
        links: 
            - php

    php:
        container_name: php-instagram
        build: ./php
        volumes:
            - ../instagram:/app
        links:
            - mysql
        user: 1000:1000
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: lj7teANDmbIUKlLCyigctWuVL7MXafUw
            APP_TIMEZONE: Europe/Moscow
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: instagram
            DB_USERNAME: instagram
            DB_PASSWORD: 123
            CACHE_DRIVER: file
            QUEUE_DRIVER: sync
            XDEBUG_CONFIG: remote_host=172.17.0.1

    mysql:
        image: percona
        container_name: percona-container
        user: 1000:1000
        environment:
            MYSQL_ROOT_PASSWORD: aBUOQO
            MYSQL_DATABASE: instagram
            MYSQL_USER: instagram
            MYSQL_PASSWORD: 123
        volumes:
            - ./mysql:/var/lib/mysql
